# Generated by Django 5.2.5 on 2025-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_permission',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_permission',
        ),
        migrations.AddField(
            model_name='post',
            name='authenticated_access',
            field=models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('write', 'Read & Write')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='author_access',
            field=models.CharField(choices=[('write', 'Read & Write')], default='write', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='public_access',
            field=models.CharField(choices=[('none', 'None'), ('read', 'Read Only')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='team_access',
            field=models.CharField(choices=[('none', 'None'), ('read', 'Read Only'), ('write', 'Read & Write')], default='none', max_length=10),
        ),
    ]
